"""make notification unlock_id nullable

Revision ID: 5a19892b57c8
Revises: fd4d2f22004a
Create Date: 2026-04-05 19:03:50.818924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a19892b57c8'
down_revision = 'fd4d2f22004a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('unlock_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('unlock_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
